# Generated by Django 5.0.4 on 2024-04-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='creaate',
            new_name='create',
        ),
    ]
